# Generated by Django 3.1.1 on 2022-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Revenue_Date', models.DateField(auto_now=True)),
                ('Funds_Cleared_Date', models.DateField(auto_now=True)),
                ('From', models.CharField(max_length=50)),
                ('Percentage_For_Tahir', models.FloatField()),
                ('Percentage_For_Sohail', models.FloatField()),
                ('Total_Price', models.FloatField()),
                ('Getting_Price', models.FloatField()),
                ('Is_Blocked', models.BooleanField(verbose_name='')),
            ],
        ),
    ]
