# Generated by Django 3.1.1 on 2022-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrecords', '0002_auto_20220129_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='Selling_Key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
