# Generated by Django 3.1.1 on 2022-01-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrecords', '0003_userrecord_selling_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='Is_Blocked',
            field=models.BooleanField(verbose_name='Is Blocked'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='Selling_Key',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
