# Generated by Django 3.1.1 on 2022-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrecords', '0004_auto_20220129_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='Selling_Key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
