# Generated by Django 4.0.1 on 2022-01-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahircreativecustomers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='Funds_Cleared_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='Order_Revenue_Date',
            field=models.DateField(),
        ),
    ]
