# Generated by Django 3.1.1 on 2022-02-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahircreativecustomers', '0002_alter_userrecord_funds_cleared_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('requirments', models.CharField(max_length=250)),
                ('user_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahircreativecustomers.userrecord')),
            ],
        ),
    ]
