# Generated by Django 3.1.1 on 2022-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahircreativecustomers', '0006_options_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='options',
            field=models.ManyToManyField(default=None, to='tahircreativecustomers.Options'),
        ),
    ]
