# Generated by Django 3.1.1 on 2022-02-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tahircreativecustomers', '0007_auto_20220210_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
