# Generated by Django 3.1.1 on 2022-02-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahircreativecustomers', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible',
            field=models.BooleanField(default='False'),
        ),
    ]
